contact_links:
  - name: 🙌 Contribution Guide
    url: https://github.com/hoangmanhkhiem/contribute
    about: Please read through before making contributions.
  - name: 💬 Anthony's Discord Server
    url: https://chat.hoangmanhkhiem.me/
    about: Want to discuss / chat with the community? Here you go!
  - name: ⁉️ Why and How to make a reproduction?
    url: https://hoangmanhkhiem.me/posts/why-reproductions-are-required
    about: Reproduction is very important for maintainer to help on your issues!
